services:
  # Backend service
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: |
      cd chatbot/chatbot_backend
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      cd chatbot/chatbot_backend
      gunicorn chatbot_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatbot_backend.settings
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

  # Frontend service
  - type: web
    name: chatbot-frontend
    env: node
    buildCommand: |
      cd chatbot
      npm install
      npm run build
    startCommand: |
      cd chatbot
      npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://chatbot-backend.onrender.com 